// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_4lAAojQhHLkTT5HbdXsMVUiPeaG_iqQ',
    appId: '1:163690254458:web:2cad1054c1fdf5e79dabc3',
    messagingSenderId: '163690254458',
    projectId: 'onco50',
    authDomain: 'onco50.firebaseapp.com',
    storageBucket: 'onco50.firebasestorage.app',
    measurementId: 'G-CKYX8XKL82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrOfnXtifsvW1xp4c9S61FIClVycV3bxs',
    appId: '1:163690254458:android:ece58dcd92b1ff4d9dabc3',
    messagingSenderId: '163690254458',
    projectId: 'onco50',
    storageBucket: 'onco50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCgG6a_8-chTXbg986yHOqbJvmREF9_x4',
    appId: '1:163690254458:ios:8f78f61a9c0628cc9dabc3',
    messagingSenderId: '163690254458',
    projectId: 'onco50',
    storageBucket: 'onco50.firebasestorage.app',
    iosBundleId: 'com.example.onco50',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCgG6a_8-chTXbg986yHOqbJvmREF9_x4',
    appId: '1:163690254458:ios:8f78f61a9c0628cc9dabc3',
    messagingSenderId: '163690254458',
    projectId: 'onco50',
    storageBucket: 'onco50.firebasestorage.app',
    iosBundleId: 'com.example.onco50',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_4lAAojQhHLkTT5HbdXsMVUiPeaG_iqQ',
    appId: '1:163690254458:web:9772b93a79b8358e9dabc3',
    messagingSenderId: '163690254458',
    projectId: 'onco50',
    authDomain: 'onco50.firebaseapp.com',
    storageBucket: 'onco50.firebasestorage.app',
    measurementId: 'G-GWDM7K07HK',
  );

}