import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart'; // Firebase Core 
import 'firebase_options.dart'; // Generated by flutterfire configure
import 'InitialFlashScreen/introFlashScreen.dart';

// The main entry point for the Flutter application.
void main() async {
  // Ensures all bindings are initialized before Firebase
  WidgetsFlutterBinding.ensureInitialized();
  // Initialize Firebase
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const MyApp());
}


// The root widget of the application.
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'AI Drug Concentration App',
      theme: ThemeData(
        // Swiggy-like primary color
        primarySwatch: Colors.brown,
        // Using a clear and modern font.
        fontFamily: 'Inter',
        // Setting a clean white background.
        scaffoldBackgroundColor: Colors.white,
        inputDecorationTheme: InputDecorationTheme(
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(8.0), // Less rounding
            borderSide: const BorderSide(color: Colors.grey, width: 1.0),
          ),
          filled: true,
          fillColor: Colors.grey[50], // Very light grey fill
          hintStyle: TextStyle(color: Colors.grey[500]),
          // Slightly reduced padding for a cleaner look
          contentPadding: const EdgeInsets.symmetric(
            vertical: 16.0,
            horizontal: 16.0,
          ),
        ),
      ),
      // After Firebase init, show your splash/intro screen
      home: const SplashWrapper(),
    );
  }
}
